### ISSUE TITLE
Running `htmlbin server` throws `bind undefined`

### ISSUE THREAD

**Issue by saibotsivad** [substack/htmlbin#1]
I ran the install: `npm install -g htmlbin`

Then I ran the server using the command in the example: `htmlbin server -p 8000`

After this it threw the following error:

```
$  htmlbin server -p 8000
/Users/saibotsivad/Development/npm_global/lib/node_modules/htmlbin/node_modules/tcp-bind/index.js:33
    throw ex;
          ^
Error: bind undefined
    at error (/Users/tobias/Development/npm_global/lib/node_modules/htmlbin/node_modules/tcp-bind/index.js:30:14)
    at module.exports (/Users/tobias/Development/npm_global/lib/node_modules/htmlbin/node_modules/tcp-bind/index.js:17:9)
    at Object.<anonymous> (/Users/tobias/Development/npm_global/lib/node_modules/htmlbin/bin/cmd.js:21:15)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:863:3
```

I'm using iojs v1.4.2

```
$  iojs -v
v1.4.2
```

**Comment by substack** [comment]
I just upgraded tcp-bind which has the fix. Try now in htmlbin version 2.1.2.

**Comment by saibotsivad** [comment]
Works great now, thanks so much!
